### PR TITLE
Added Auth Routes

### PR DESCRIPTION
**Pull request by prakhar728**
Added auth routes using JWT, bcryptjs for password hashing and Joi for validation.

The api end points are 
`/api/user/register` for registering. 

`/api/user/login` for login.

### CODE REVIEW

**Review by madrix01 — APPROVED** [review]
Good work. You shouldn't add comments for obvious things like import and export.

**Comment by prakhar728** [comment]
> Good work. You shouldn't add comments for obvious things like import and export.

I'll keep this in mind

**Comment by madrix01** [comment]
@prakhar728 Create `README.md` file in `backend` describing the URI endpoints for frontend

**Comment by prakhar728** [comment]
> @prakhar728 Create `README.md` file in `backend` describing the URI endpoints for frontend

I'll make the required changes and create a new PR.  The Repo from my local machine was deleted.

**Pull request merged**
